[workspace]
resolver = "2"
members = [
    "day-01",
    "day-02",
    "day-03",
    "day-04",
    "day-05",
    "day-06",
    "day-07",
    "day-08",
]

[workspace.dependencies]
rayon = "1.8.0"
regex = "1.10.2"
num = "0.4.1"